apiVersion: v1
kind: Service
metadata:
  name: ca-authoring-service
  namespace: collaborative-authoring
  labels:
    app: ca-authoring-service
    service: ca-authoring-service
spec:
  selector:
    app: ca-authoring-service-pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-authoring-service
  namespace: collaborative-authoring
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ca-authoring-service-pod
      version: latest
  template:
    metadata:
      labels:
        app: ca-authoring-service-pod
        version: latest
    spec:
      containers:
        - name: ca-authoring-container
          image: eu.gcr.io/s64-1-vetis/raphael/collaborative-authoring/ca-authoring-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 250Mi
              cpu: 200m
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcr-json-key      