name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#This declares the pipeline stages  
stages:
  - build
  - test
  - ContainerBuild
  - deployment

jobs:
  build:
    before_script:
    - "cd src"
    - "dotnet restore"
    stage: build
    steps: 
      - uses: actions/checkout@v2
      - name: Setup .NET
      - run: dotnet publish -c Release
	uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

  test:
    before_script:
    - "cd src"
    - "dotnet restore"
    stage: test
    steps:
      - run: dotnet test /p:CollectCoverage=true

#build_authorization_service:
#  stage: ContainerBuild
#  image:
#    name: gcr.io/kaniko-project/executor:debug
#    entrypoint: [""]
#  only:
#    variables:
#      - $CI_COMMIT_REF_NAME =~ /master/
#  script:
#    - mkdir -p /kaniko/.docker/
#   - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/src/vetis-authorization-service.Dockerfile --destination $CI_REGISTRY_IMAGE/vetis-authorization-service:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE/vetis-authorization-service:latest
